// parsers/cpp/comm_df/comm_df_frame_types.h
// AUTO-GENERATED by tools/icd_codegen from ICD_COMM_DF_v3.xlsx
// DO NOT EDIT MANUALLY — re-run codegen if ICD changes
#pragma once
#include <cstdint>

namespace comm_df {

    // ── Frame magic bytes ─────────────────────────────────────────────────────
    constexpr uint8_t CMD_HEADER[4]  = {0xAA, 0xAB, 0xBA, 0xBB};
    constexpr uint8_t RESP_HEADER[4] = {0xEE, 0xEF, 0xFE, 0xFF};
    constexpr uint8_t SCD_HEADER[2]  = {0xAA, 0xAA};

    constexpr uint8_t CMD_FOOTER[4]  = {0xCC, 0xCD, 0xDC, 0xDD};
    constexpr uint8_t RESP_FOOTER[4] = {0xFF, 0xFE, 0xEF, 0xEE};
    constexpr uint8_t SCD_FOOTER[2]  = {0xEE, 0xEE};

    // ── Frame layout sizes (bytes) ────────────────────────────────────────────
    //
    // CMD frame layout:
    //   [header:4][length:4][group_id:2][unit_id:2][payload:N][crc:2][footer:4]
    //
    // RESP frame layout:
    //   [header:4][length:4][group_id:2][unit_id:2][status:2][payload:N][crc:2][footer:4]
    //
    // SCD frame layout:
    //   [header:2][length:2][payload:N][crc:1][footer:2]

    constexpr int CMD_HEADER_SIZE  = 12; // header(4) + length(4) + group_id(2) + unit_id(2)
    constexpr int CMD_FOOTER_SIZE  =  6; // crc(2) + footer(4)
    constexpr int CMD_OVERHEAD     = CMD_HEADER_SIZE + CMD_FOOTER_SIZE;

    constexpr int RESP_HEADER_SIZE = 14; // header(4) + length(4) + group_id(2) + unit_id(2) + status(2)
    constexpr int RESP_FOOTER_SIZE =  6; // crc(2) + footer(4)
    constexpr int RESP_OVERHEAD    = RESP_HEADER_SIZE + RESP_FOOTER_SIZE;

    constexpr int SCD_HEADER_SIZE  =  4; // header(2) + length(2)
    constexpr int SCD_FOOTER_SIZE  =  3; // crc(1) + footer(2)
    constexpr int SCD_OVERHEAD     = SCD_HEADER_SIZE + SCD_FOOTER_SIZE;

    constexpr int MAX_PAYLOAD      = 1048576; // 1 MB hard cap

    // ── Byte offsets for fields within a raw frame buffer ────────────────────
    constexpr int OFFSET_LENGTH    = 4;  // uint32 payload length (both CMD and RESP)
    constexpr int OFFSET_GROUP_ID  = 8;  // uint16 group_id       (both CMD and RESP)
    constexpr int OFFSET_UNIT_ID   = 10; // uint16 unit_id         (both CMD and RESP)
    constexpr int OFFSET_STATUS    = 12; // uint16 status          (RESP only)

    // ── Group IDs ─────────────────────────────────────────────────────────────
    constexpr uint16_t GROUP_SYSTEM_MGMT  = 100;
    constexpr uint16_t GROUP_RF_CONTROL   = 101;
    constexpr uint16_t GROUP_MEASUREMENT  = 102;
    constexpr uint16_t GROUP_GNSS         = 103;

    // ── Group 100 — System Management ────────────────────────────────────────
    constexpr uint16_t CMD_GET_SYSTEM_VERSION  = 1;
    constexpr uint16_t RESP_SYSTEM_VERSION     = 2;
    constexpr uint16_t CMD_SET_DEVICE_ID       = 3;
    constexpr uint16_t RESP_SET_DEVICE_ID      = 4;
    constexpr uint16_t CMD_RESET               = 5;
    constexpr uint16_t RESP_RESET              = 6;

    // ── Group 101 — RF Control ────────────────────────────────────────────────
    constexpr uint16_t CMD_SET_FREQUENCY       = 1;
    constexpr uint16_t RESP_SET_FREQUENCY      = 2;
    constexpr uint16_t CMD_SET_THRESHOLD       = 3;
    constexpr uint16_t RESP_SET_THRESHOLD      = 4;
    constexpr uint16_t CMD_SET_BANDWIDTH       = 5;
    constexpr uint16_t RESP_SET_BANDWIDTH      = 6;
    constexpr uint16_t CMD_SET_GAIN            = 7;
    constexpr uint16_t RESP_SET_GAIN           = 8;

    // ── Group 102 — Measurement ───────────────────────────────────────────────
    constexpr uint16_t CMD_REQUEST_SCAN        = 1;
    constexpr uint16_t RESP_SCAN_RESULT        = 2;
    constexpr uint16_t CMD_REQUEST_AOA         = 3;
    constexpr uint16_t RESP_AOA_RESULT         = 4;
    constexpr uint16_t CMD_REQUEST_FFT         = 5;
    constexpr uint16_t RESP_FFT_RESULT         = 6;

    // ── Group 103 — GNSS ─────────────────────────────────────────────────────
    constexpr uint16_t CMD_GET_POSITION        = 1;
    constexpr uint16_t RESP_POSITION           = 2;
    constexpr uint16_t CMD_GET_SATELLITES      = 3;
    constexpr uint16_t RESP_SATELLITES         = 4;

    // ── Status codes (in RESP frames) ────────────────────────────────────────
    constexpr uint16_t STATUS_OK               = 0;
    constexpr uint16_t STATUS_INVALID_PARAM    = 1;
    constexpr uint16_t STATUS_DEVICE_BUSY      = 2;
    constexpr uint16_t STATUS_HW_ERROR         = 3;
    constexpr uint16_t STATUS_NOT_SUPPORTED    = 4;

} // namespace comm_df
