#!/usr/bin/env python3
"""Build DP-ECM-1071 HF request/response test-tracking spreadsheet (.xlsx).

Source of truth: dp_ecm_hf_parser.cpp dispatch tables (parse_message /
format_response), cross-checked against decoder header comments.
CMD (request) frame overhead = 16 bytes (4 hdr + 4 size + 2 group + 2 unit + 4 ftr).
RESP (response) frame overhead = 18 bytes (4 hdr + 2 status + 4 size + 2 group + 2 unit + 4 ftr).
"""
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from make_xlsx import build_workbook

CMD_OVERHEAD = 16
RESP_OVERHEAD = 18

# (group_id, unit_id, direction["Request"/"Response"], message_name, payload_size, icd_table, notes)
# payload_size: int (fixed bytes) or a string describing variable size / unknown
ROWS = [
(1,1,"Request","Get System Version cmd",0,"","MRx, shared with VU"),
(1,2,"Response","Get System Version Details response",16,"",""),
(1,3,"Request","Get Checksum cmd",0,"",""),
(1,4,"Response","Get Checksum Details response",1024,"Table 201",""),
(1,5,"Request","PBIT cmd",0,"",""),
(1,6,"Response","PBIT Status response",120,"Table 203",""),
(1,7,"Request","IBIT cmd",0,"",""),
(1,8,"Response","IBIT Status response",112,"",""),
(1,9,"Request","Temperature cmd",0,"",""),
(1,10,"Response","Temperature Status response (9 floats)",36,"Table 212/213",""),
(1,13,"Request","Fan Speed cmd",0,"",""),
(1,14,"Response","Fan Speed Status response",4,"","Same layout as ECM 100/14"),
(1,17,"Request","UART Test cmd",4,"",""),
(1,18,"Response","UART Test response",4,"","Same layout as ECM 100/18"),
(1,25,"Request","CBIT cmd",0,"",""),
(1,26,"Response","CBIT Status response",8,"",""),
(1,33,"Request","Close All Channels cmd",0,"",""),
(1,34,"Response","Close All Channels ACK",0,"",""),
(3,1,"Request","Read Board Count cmd",0,"",""),
(3,2,"Response","Read Board Count response",4,"",""),
(3,17,"Request","Read Channel Info cmd",0,"",""),
(3,18,"Response","Read Channel Information response",16,"","8x uint16 channel status"),
(3,19,"Request","Write Channel Information cmd",4,"",""),
(3,20,"Response","Write Channel ACK",0,"",""),
(3,21,"Request","VUSHF Channel Status cmd",0,"",""),
(3,22,"Response","MRX Individual Channel Init Status response",16,"Table 219","8x uint16, 1=success/0=fail"),
(3,23,"Request","Read Tuning Details cmd",0,"",""),
(3,24,"Response","Read MRx and SRx Tuning Details response",8,"",""),
(3,25,"Request","Get CBIT Status cmd",0,"",""),
(3,26,"Response","Get CBIT Status response",8,"","Shares decoder with 1/26"),
(4,5,"Request","Set Threshold cmd",8,"",""),
(4,6,"Response","Set Threshold ACK",0,"",""),
(4,7,"Request","Audio Data Acquisition cmd",4,"","Name inferred"),
(4,8,"Response","Audio Data Acquisition response","variable (4 + 2*audio_data_size, max 262144 samples)","Table 225",""),
(4,9,"Request","Audio Start Play cmd",4,"","Name inferred"),
(4,10,"Response","Audio Start Play ACK",0,"",""),
(4,11,"Request","Audio Stop Play cmd",4,"","Name inferred"),
(4,12,"Response","Audio Stop Play ACK",0,"",""),
(4,15,"Request","Audio FIFO Reset cmd",4,"","Name inferred"),
(4,16,"Response","Audio FIFO Reset ACK",0,"",""),
(4,17,"Request","Demodulation and Bandwidth Selection cmd",8,"",""),
(4,18,"Response","Demod/BW Select ACK",0,"",""),
(4,23,"Request","Start IQ Data Logging cmd",20,"",""),
(4,24,"Response","IQ Start/Status response",4,"","Shared decoder, also used for 4/34"),
(4,25,"Request","Stop IQ Data Logging cmd",4,"","Name inferred"),
(4,26,"Response","Stop IQ Data Logging response",132,"","Includes 128-char file_path"),
(4,33,"Request","Start IQ Data Streaming cmd",4,"",""),
(4,34,"Response","IQ Start/Status response",4,"","Shares decoder with 4/24"),
(4,35,"Request","Stop IQ Data Streaming cmd",4,"","Name inferred"),
(4,36,"Response","Stop IQ Streaming ACK",0,"",""),
(4,39,"Request","Configure Memory Scan cmd","variable (8 + 12*freq_count, max 10000)","","Shares decoder with 4/41"),
(4,40,"Response","Configure Memory Scan ACK",0,"",""),
(4,41,"Request","Read/Start Memory Scan cmd","variable (8 + 12*freq_count, max 10000)","","Shares decoder with 4/39"),
(4,42,"Response","Read Memory Scan Data response","variable (8 + 20*count, max 10000)","Table 239/240",""),
(4,43,"Request","DDC FFT Data cmd",4,"","Name inferred"),
(4,44,"Response","DDC FFT Data response","variable (4 + 4*bin_count, max 16388)","","Header comment says fixed 16388B but code is bin_count-driven"),
(4,53,"Request","Engage Channel cmd",12,"",""),
(4,54,"Response","Engage Channel ACK",0,"",""),
(4,55,"Request","Disengage Channel cmd",4,"","Name inferred"),
(4,56,"Response","Disengage Channel ACK",0,"",""),
(4,57,"Request","Stop Memory Scan cmd",4,"","Name inferred"),
(4,58,"Response","Stop Memory Scan ACK",0,"",""),
(4,59,"Request","Smart Memory Scan Config cmd",4,"","Name inferred"),
(4,60,"Response","Smart Memory Scan Config ACK",0,"",""),
(4,61,"Request","Read Smart Memory Scan Data cmd",12,"",""),
(4,62,"Response","Read Smart Memory Scan Data response",16,"",""),
(4,63,"Request","Stop Smart Memory Scan cmd",4,"","Name inferred"),
(4,64,"Response","Stop Smart Memory Scan ACK",0,"",""),
(4,65,"Request","Start IQ Data Streaming to GO2Monitor Optical cmd",4,"",""),
(4,66,"Response","Start Optical IQ ACK",0,"",""),
(4,67,"Request","Stop Optical IQ cmd",4,"",""),
(4,68,"Response","Stop Optical IQ ACK",0,"",""),
(4,69,"Request","Read Optical Port Availability Status cmd",4,"",""),
(4,70,"Response","Read Optical Port Availability Status response",12,"",""),
(4,71,"Request","Read Optical Interface IP Address cmd",4,"",""),
(4,72,"Response","Read Optical Interface IP Address response",24,"","IP(4B) + 9x port_id(u16)"),
(5,1,"Request","Set Center Frequency cmd",12,"",""),
(5,2,"Response","Set Center Freq ACK",0,"",""),
(5,3,"Request","Attenuation Selection cmd",16,"Table 256",""),
(5,4,"Response","Attenuation Select ACK",0,"",""),
(5,9,"Request","Clear Center Freq cmd",4,"",""),
(5,10,"Response","Clear Center Freq ACK",0,"",""),
(5,13,"Request","Read AGC/MGC cmd",0,"",""),
(5,14,"Response","Read AGC/MGC Attenuation response",4,"",""),
(6,7,"Request","FH Monitoring Configuration cmd",52,"",""),
(6,8,"Response","FH Monitoring Config ACK",0,"",""),
(6,9,"Request","GO2Monitor Connection Establishment cmd",260,"Table 258",""),
(6,10,"Response","GO2Monitor Connect ACK",0,"",""),
(6,11,"Request","GO2Monitor Disconnect cmd",0,"",""),
(6,12,"Response","GO2Monitor Disconnect ACK",0,"",""),
(6,13,"Request","Start GO2Monitor Transmission cmd",144,"",""),
(6,14,"Response","Start GO2Monitor Transmission ACK",0,"","Possible wiring gap - decoder not actually called"),
(6,15,"Request","Stop GO2Monitor cmd",0,"",""),
(6,16,"Response","Stop GO2Monitor ACK",0,"",""),
(7,1,"Request","Signal BITE cmd",12,"",""),
(7,2,"Response","Signal BITE response",16,"",""),
(7,3,"Request","BITE/Antenna Select cmd",4,"",""),
(7,4,"Response","BITE/Antenna Select ACK",0,"",""),
(7,5,"Request","Reference Source Select cmd",4,"",""),
(7,6,"Response","Ref Source Select ACK",0,"",""),
(7,9,"Request","AFC Enable/Disable cmd",4,"",""),
(7,10,"Response","AFC ACK",0,"",""),
(7,11,"Request","RF Squelch cmd",4,"",""),
(7,12,"Response","RF Squelch ACK",0,"",""),
(7,13,"Request","IQ Socket Open cmd",4,"",""),
(7,14,"Response","IQ Socket Open ACK",0,"",""),
(7,15,"Request","IQ Socket Close cmd",4,"",""),
(7,16,"Response","IQ Socket Close ACK",0,"",""),
(7,17,"Request","Spectrum Average Count Selection cmd",8,"Table 285",""),
(7,18,"Response","Spectrum Avg Count ACK",0,"",""),
(7,19,"Request","Smart RF AGC cmd",4,"",""),
(7,20,"Response","Smart RF AGC ACK",0,"",""),
(7,21,"Request","Audio Squelch cmd",8,"",""),
(7,22,"Response","Audio Squelch ACK",0,"",""),
(7,23,"Request","Set Date and Time cmd",8,"","Same layout as ECM 109/11"),
(7,24,"Response","Set Date/Time ACK",0,"",""),
(100,1,"Request","Get System Version cmd",0,"",""),
(100,2,"Response","Get System Version Details response",20,"","README top summary says 28B - stale, code is 20B"),
(100,3,"Request","Get SRX Checksum cmd",0,"",""),
(100,4,"Response","SRx Checksum response",1024,"","README top summary says 1000B (VU size) - stale"),
(100,5,"Request","Get PBIT Status cmd",0,"",""),
(100,6,"Response","PBIT Status response",24,"","README top summary says 88B - stale"),
(100,7,"Request","Get IBIT Status cmd",0,"",""),
(100,8,"Response","IBIT Status response",8,"Table 10","README top summary says 68B - stale"),
(100,9,"Request","Get Temperature cmd",0,"",""),
(100,10,"Response","Temperature Status response (6 floats)",24,"Table 16","README top summary says 36B/9 floats - stale"),
(100,11,"Request","Set Fan Speed cmd",4,"",""),
(100,12,"Response","Set Fan Speed ACK",0,"",""),
(100,13,"Request","Fan Speed Status cmd",0,"",""),
(100,14,"Response","Fan Speed Status response",4,"","Same as VU"),
(100,15,"Request","Ethernet Test cmd",0,"",""),
(100,16,"Response","Ethernet Test Status response",12,"",""),
(100,17,"Request","UART Port Select cmd",4,"",""),
(100,18,"Response","UART Test Status response",4,"","Same as VU"),
(100,21,"Request","Fan Voltage Status cmd",0,"",""),
(100,22,"Response","Fan Voltage Status response (6 floats)",24,"",""),
(100,23,"Request","PPS Test cmd",0,"",""),
(100,24,"Response","PPS Test Status response",16,"",""),
(100,25,"Request","RS422 Test cmd",0,"",""),
(100,26,"Response","RS422 Test Status response","unknown - raw_hex fallback, no struct decoder","",""),
(100,27,"Request","FPGA Temperature cmd",0,"",""),
(100,28,"Response","FPGA Temperature Details response",4,"",""),
(100,29,"Request","CBIT Status cmd",0,"",""),
(100,30,"Response","CBIT Status response",4,"","README references unit 26/8B - stale; actual is unit 30, 4B"),
(101,25,"Request","Set Threshold cmd",8,"Table 39",""),
(101,26,"Response","Set Threshold ACK",0,"",""),
(101,27,"Request","Set Resolution cmd",4,"Table 41",""),
(101,28,"Response","Set Resolution ACK",0,"",""),
(101,31,"Request","Start Follow-On Jamming cmd",44,"Table 115","Shared decoder with 200/17"),
(101,32,"Response","Start Follow-on Jam ACK",0,"",""),
(101,33,"Request","Stop Follow-on Jam cmd",0,"",""),
(101,34,"Response","Stop Follow-on Jam ACK",0,"",""),
(101,37,"Request","Configure Detection cmd",12,"Table 47",""),
(101,38,"Response","Configure Detection ACK",0,"",""),
(101,39,"Request","Start FH Detection cmd",8,"Table 51",""),
(101,40,"Response","FH Detection response","variable (4 + 40*hopper_count)","","HF S_HOPPER_DATA=40B vs VU=60B"),
(101,43,"Request","Get Wideband FFT Data cmd",8,"Table 49",""),
(101,44,"Response","Wideband FFT Data response",6408,"Table 50",""),
(101,47,"Request","Set Min/Max Pulse Range cmd",16,"Table 43",""),
(101,48,"Response","Set Pulse Range ACK",0,"",""),
(101,55,"Request","Set Minimum Hops Count cmd",4,"Table 45",""),
(101,56,"Response","Set Min Hops ACK",0,"",""),
(101,63,"Request","Set Auto/Manual Tracking Configuration cmd",4,"",""),
(101,64,"Response","Auto/Manual Tracking ACK",0,"",""),
(101,69,"Request","Start FF Detection cmd",8,"Table 53",""),
(101,70,"Response","FF Detection response","variable (6408 fixed + 4 + 36*ff_count)","Table 50/54/62",""),
(101,73,"Request","Start List (FF & Burst) Jamming cmd",1228,"Table 121","Shared decoder with 200/11"),
(101,74,"Response","Start List Jam ACK",0,"",""),
(101,75,"Request","Stop List Jam cmd",0,"",""),
(101,76,"Response","Stop List Jam ACK",0,"",""),
(101,79,"Request","Send ECM Reports cmd",4,"","Shared decoder w/ 200/9"),
(101,80,"Response","Send ECM Reports ACK",0,"",""),
(101,83,"Request","Start Burst Detection cmd",8,"Table 57",""),
(101,84,"Response","Burst Detection response","variable (4 + 24*burst_count, max 1600)","Table 58",""),
(101,85,"Request","Start Scan Speed cmd",8,"Table 59",""),
(101,86,"Response","Start Scan Speed ACK",0,"",""),
(101,87,"Request","Stop Scan Speed cmd",0,"",""),
(101,88,"Response","Stop Scan Speed response",57604,"Table 62","Fixed: 4 + 36*1600"),
(101,92,"Request","Start Responsive Sweep Jam cmd",208,"Table 131","Shared decoder with 200/21"),
(101,93,"Response","Start Responsive Sweep Jam ACK",0,"",""),
(101,94,"Request","Get Zoom Band FFT Data cmd",16,"Table 71",""),
(101,95,"Response","Zoom Band FFT Data response","variable (4*sample_count, max 6400)","","Same as VU"),
(101,100,"Request","Set Flatness Mode cmd",12,"",""),
(101,101,"Response","Set Flatness Mode ACK",0,"",""),
(101,102,"Request","Set Integration Time cmd",4,"",""),
(101,103,"Response","Set Integration Time ACK",0,"",""),
(101,104,"Request","Set Multi-Band FH Mode cmd",4,"",""),
(101,105,"Response","Set Multi-Band FH Mode ACK",0,"",""),
(101,106,"Request","Set Narrow Band FH cmd",4,"",""),
(101,107,"Response","Set Narrow Band FH ACK",0,"",""),
(101,140,"Request","HF-specific cmd",0,"","No further description in code comment"),
(101,141,"Response","HF-specific ACK",0,"",""),
(101,158,"Request","Terminate FFT Thread cmd",4,"Table 55",""),
(101,159,"Response","Terminate FFT ACK",0,"",""),
(101,160,"Request","HF slow scan sequence cmd",0,"",""),
(101,161,"Response","HF slow scan ACK",0,"",""),
(101,162,"Request","HF slow scan sequence cmd",0,"",""),
(101,163,"Response","HF slow scan ACK",0,"",""),
(101,164,"Request","HF slow scan sequence cmd",0,"",""),
(101,165,"Response","HF slow scan ACK",0,"",""),
(101,174,"Request","HF slow scan sequence cmd",0,"",""),
(101,175,"Response","HF slow scan ACK",0,"",""),
(101,176,"Request","HF slow scan sequence cmd",0,"",""),
(101,177,"Response","HF slow scan ACK",0,"",""),
(101,178,"Request","HF slow scan sequence cmd",0,"",""),
(101,179,"Response","HF slow scan ACK",0,"",""),
(101,182,"Request","HF fast scan sequence cmd",0,"",""),
(101,183,"Response","HF fast scan ACK",0,"",""),
(101,184,"Request","HF fast scan sequence cmd",0,"",""),
(101,185,"Response","HF fast scan ACK",0,"",""),
(101,186,"Request","HF fast scan sequence cmd",0,"",""),
(101,187,"Response","HF fast scan ACK",0,"",""),
(101,200,"Request","HF wideband cmd",0,"",""),
(101,201,"Response","HF wideband ACK",0,"",""),
(101,202,"Request","HF wideband cmd",0,"",""),
(101,203,"Response","HF wideband ACK",0,"",""),
(101,204,"Request","HF data query cmd",0,"","Response arrives on 101/205, not paired the usual way"),
(101,205,"Response","HF data response","unknown - no struct decoder, raw_hex fallback","",""),
(101,210,"Request","HF cmd (cross-group)",0,"","Response for this cmd is on Group 111 unit 211, not 101/211"),
(106,1,"Request","Start Immediate Jam (Single Frequency) cmd",28,"Table 152",""),
(106,2,"Response","Start Immediate Jam ACK",0,"",""),
(106,3,"Request","Generate Multi Frequency TDM cmd",80,"Table 158",""),
(106,4,"Response","TDM Jam ACK",0,"",""),
(106,5,"Request","Generate Multi Carrier FDM cmd",68,"Table 160",""),
(106,6,"Response","FDM Jam ACK",0,"",""),
(106,9,"Request","Stop Immediate Jamming cmd",0,"",""),
(106,10,"Response","Stop Jamming response",4,"Table 171",""),
(106,21,"Request","Enable/Disable Power Amplifier cmd",4,"Table 174",""),
(106,22,"Response","Enable PA ACK",0,"",""),
(106,39,"Request","Configure External Modulation Jam Data cmd",8196,"Table 154",""),
(106,40,"Response","Configure External Modulation response",4,"","Same as VU 106/40"),
(106,41,"Request","Generate Sweep Frequency cmd",192,"Table 162",""),
(106,42,"Response","Sweep Jam ACK",0,"",""),
(106,45,"Request","Enable/Disable PA and SDU Controls cmd",4,"Table 172",""),
(106,46,"Response","Enable PA+SDU ACK",0,"",""),
(106,49,"Request","Configure Programmable Exciter Modulating Signal cmd",2052,"Table 156",""),
(106,50,"Response","Configure Prog Exciter ACK",0,"",""),
(106,54,"Response","Start Immediate Jam ACK (HF-specific extended status)",8,"","Response-only unit; no matching cmd case (106/53) in dispatch table"),
(106,55,"Request","Generate Comb Noise cmd",20,"Table 167",""),
(106,56,"Response","Comb Noise ACK",0,"",""),
(109,11,"Request","Set Date and Time cmd",8,"","Same as VU"),
(109,12,"Response","Set Date Time ACK",0,"",""),
(109,15,"Request","Send Auto Threshold Value cmd",0,"","Not in README top summary"),
(109,16,"Response","Auto Threshold Value response",6404,"Table 180/181","4 + 1600 floats"),
(109,17,"Request","Acquire Hopper Channelization cmd",0,"","Not in README top summary"),
(109,18,"Response","Hopper Channelization Data response","variable (8 + 28*count, max 16384)","Table 183",""),
(111,3,"Request","Signal BITE Test cmd",16,"","HF-specific; VU equivalent is 111/21 at 4B"),
(111,4,"Response","Signal BITE Test response",12,"",""),
(111,5,"Request","Reference Input Selection cmd",4,"","Same as VU"),
(111,6,"Response","Reference Input ACK",0,"",""),
(111,7,"Request","Module HEALTH Status cmd",0,"","Not in README top summary"),
(111,8,"Response","Module HEALTH Status response",4,"",""),
(111,9,"Request","Send Protected Scan List cmd","variable (4 + 8*protected_band_count)","","Same as VU"),
(111,10,"Response","Send Protected Scan List ACK",0,"",""),
(111,13,"Request","Protected Scan Enable/Disable cmd",4,"","Same as VU"),
(111,14,"Response","Protected Scan Enable ACK",0,"",""),
(111,15,"Request","PDW Channelization cmd",0,"",""),
(111,16,"Response","PDW Channelization Data response","variable (8 + 28*count, max 16384)","page 64",""),
(111,17,"Request","FH Splitband Enable/Disable cmd",4,"","Same as VU"),
(111,18,"Response","FH Splitband Enable ACK",0,"",""),
(111,19,"Request","Send FH Splitband Frequency cmd",4,"","Same as VU"),
(111,20,"Response","FH Splitband Freq ACK",0,"",""),
(111,21,"Request","Signal BITE Test (band select) cmd",4,"Sec 3.2.1.3.1",""),
(111,22,"Response","Observed BITE Frequency response",16,"",""),
(111,23,"Request","Send Spectrum Protected-Band Enable/Disable cmd",4,"","Not in README top summary"),
(111,24,"Response","Spectrum Protected Band ACK",0,"",""),
(111,25,"Request","Get Storage Details cmd",0,"","Not in README top summary"),
(111,26,"Response","Get Storage Details response",20,"","Same as VU"),
(111,27,"Request","Read Protected Band List cmd",0,"","Not in README top summary"),
(111,28,"Response","Read Protected Band List response","variable (4 + 8*count)","",""),
(111,29,"Request","Auto Threshold Enable/Disable cmd",4,"Sec 3.2.1.3","Not in README top summary"),
(111,30,"Response","Auto Threshold Enable ACK",0,"",""),
(111,31,"Request","Hopper Channelization Enable/Disable cmd",16,"","Not in README top summary"),
(111,32,"Response","Hopper Channelization ACK",0,"",""),
(111,211,"Response","Cross-group response to 101/210",'unknown - no struct decoder, raw_hex fallback',"",""),
(112,1,"Request","ASU/SDU Configuration cmd",8,"Table 192",""),
(112,2,"Response","ASU/SDU Enable/Disable response",4,"Table 193",""),
(112,3,"Request","TRSDU Receiver Line Status cmd",0,"",""),
(112,4,"Response","TRSDU Receiver Line Status response",4,"Table 195",""),
(112,5,"Request","PA Receiver Line Status cmd",0,"","See workbook Notes sheet re: orphaned 112/5 decoder"),
(112,6,"Response","Power Amplifier Receiver Line Status response",4,"Table 197",""),
(112,13,"Request","Simulation Mode Configuration cmd","variable (4 + optional sim params)","",""),
(112,14,"Response","Simulation Mode Config ACK",0,"",""),
(112,37,"Request","HF-specific fast scan cmd",0,"","Not in README top summary"),
(112,38,"Response","HF fast scan ACK",0,"",""),
(200,9,"Request","Send ECM Reports cmd",4,"","Shares decoder with 101/79; Group 200 absent from README top summary"),
(200,10,"Response","Send ECM Reports ACK",0,"",""),
(200,11,"Request","Start List (FF & Burst) Jamming cmd",1228,"Table 121","Shares decoder with 101/73"),
(200,12,"Response","Start List Jam ACK",0,"",""),
(200,13,"Request","Stop List Jam cmd",0,"",""),
(200,14,"Response","Stop List Jam ACK",0,"",""),
(200,15,"Request","Get List Jam Report cmd (periodic)",0,"",""),
(200,16,"Response","ECM Report / List Jam Report response","variable (4 + 8*count)","","Same as VU 108/6"),
(200,17,"Request","Start Follow-On Jamming cmd",44,"Table 115","Shares decoder with 101/31"),
(200,18,"Response","Start Follow-on Jam ACK",0,"",""),
(200,19,"Request","Stop Follow-on Jam cmd",0,"",""),
(200,20,"Response","Stop Follow-on Jam ACK",0,"",""),
(200,21,"Request","Start Responsive Sweep Jam cmd",208,"Table 131","Shares decoder with 101/92"),
(200,22,"Response","Start Responsive Sweep Jam ACK",0,"",""),
(200,23,"Request","Stop Responsive Sweep Jam cmd",0,"","Unit assumed +-1 per code comment, not ICD-confirmed"),
(200,24,"Response","Stop Responsive Sweep Jam ACK",0,"","Unit assumed per code comment, not ICD-confirmed"),
(200,41,"Request","HPASU and PA Health Status cmd",4,"Sec 5.1.10-5.1.13",""),
(200,42,"Response","HPASU and PA Health Status response",4,"",""),
(200,54,"Request","PA/SDU Health Status cmd",0,"",""),
(200,55,"Response","PA and SDU Health Status response",8,"",""),
(200,56,"Request","PA Soft Reboot cmd",4,"",""),
(200,57,"Response","PA Soft Reboot ACK",0,"",""),
]

def total_frame_size(direction, payload_size):
    if not isinstance(payload_size, int):
        return ""
    overhead = CMD_OVERHEAD if direction == "Request" else RESP_OVERHEAD
    return payload_size + overhead

header = [
    "Group ID", "Unit ID", "Direction", "Message Name",
    "Payload Size (bytes)", "Frame Overhead (bytes)", "Total Frame Size (bytes)",
    "ICD Table Ref", "Notes", "Tested (Y/N)", "Test Result", "Tester Notes",
]

data_rows = []
for group_id, unit_id, direction, name, payload, icd, notes in ROWS:
    overhead = CMD_OVERHEAD if direction == "Request" else RESP_OVERHEAD
    total = total_frame_size(direction, payload)
    data_rows.append([
        group_id, unit_id, direction, name,
        payload, overhead, total,
        icd, notes, "", "", "",
    ])

col_widths = [10, 9, 11, 46, 30, 12, 14, 14, 55, 12, 12, 30]

frame_header = ["Field", "Command (Request) Frame", "Response Frame"]
frame_rows = [
    ["Header magic (4B)", "AA AB BA BB", "EE EF FE FF"],
    ["Footer magic (4B)", "CC CD DC DD", "FF FE EF EE"],
    ["Status field", "n/a", "int16 @ offset 4"],
    ["Size field (payload length, u32)", "offset 4", "offset 6"],
    ["Group ID field (u16)", "offset 8", "offset 10"],
    ["Unit ID field (u16)", "offset 10", "offset 12"],
    ["Payload starts at", "offset 12", "offset 14"],
    ["Fixed overhead (bytes)", str(CMD_OVERHEAD), str(RESP_OVERHEAD)],
    ["Byte order (header fields)", "Big-endian", "Big-endian"],
    ["Byte order (payload, decode/CMD side)", "Little-endian (default, per-field audit in progress)", "n/a"],
    ["Byte order (payload, encode/RESP side)", "n/a", "Big-endian (confirmed 2026-07-03)"],
]
frame_col_widths = [40, 55, 45]

sheets = [
    ("HF Request-Response", header, data_rows, col_widths),
    ("Frame Header Reference", frame_header, frame_rows, frame_col_widths),
]

out_path = os.path.join(os.path.dirname(__file__), "..", "DP-ECM_HF_Request_Response_TestSheet.xlsx")
out_path = os.path.abspath(out_path)
build_workbook(sheets, out_path)
print(f"{len(data_rows)} message rows written")
