// parsers/cpp/rdfs/rdfs_frame_types.h
// AUTO-GENERATED by tools/icd_codegen from ICD_RDFS_v2.xlsx
// DO NOT EDIT MANUALLY — re-run codegen if ICD changes
#pragma once
#include <cstdint>

namespace rdfs {

    // ── Frame magic bytes ─────────────────────────────────────────────────────
    // RDFS uses the same frame envelope as COMM_DF but different group/unit IDs
    constexpr uint8_t CMD_HEADER[4]  = {0xAA, 0xAB, 0xBA, 0xBB};
    constexpr uint8_t RESP_HEADER[4] = {0xEE, 0xEF, 0xFE, 0xFF};
    constexpr uint8_t SCD_HEADER[2]  = {0xAA, 0xAA};

    constexpr uint8_t CMD_FOOTER[4]  = {0xCC, 0xCD, 0xDC, 0xDD};
    constexpr uint8_t RESP_FOOTER[4] = {0xFF, 0xFE, 0xEF, 0xEE};
    constexpr uint8_t SCD_FOOTER[2]  = {0xEE, 0xEE};

    // ── Frame overhead sizes ──────────────────────────────────────────────────
    constexpr int CMD_HEADER_SIZE  = 12;
    constexpr int CMD_FOOTER_SIZE  =  6;
    constexpr int CMD_OVERHEAD     = CMD_HEADER_SIZE + CMD_FOOTER_SIZE;

    constexpr int RESP_HEADER_SIZE = 14;
    constexpr int RESP_FOOTER_SIZE =  6;
    constexpr int RESP_OVERHEAD    = RESP_HEADER_SIZE + RESP_FOOTER_SIZE;

    constexpr int SCD_HEADER_SIZE  =  4;
    constexpr int SCD_FOOTER_SIZE  =  3;
    constexpr int SCD_OVERHEAD     = SCD_HEADER_SIZE + SCD_FOOTER_SIZE;

    constexpr int MAX_PAYLOAD      = 1048576;

    // ── Field byte offsets ────────────────────────────────────────────────────
    constexpr int OFFSET_LENGTH   = 4;
    constexpr int OFFSET_GROUP_ID = 8;
    constexpr int OFFSET_UNIT_ID  = 10;
    constexpr int OFFSET_STATUS   = 12;

    // ── Group IDs ─────────────────────────────────────────────────────────────
    constexpr uint16_t GROUP_DEVICE_CTRL  = 200;
    constexpr uint16_t GROUP_RF_SCAN      = 201;
    constexpr uint16_t GROUP_SIGNAL_DATA  = 202;
    constexpr uint16_t GROUP_DIAGNOSTICS  = 203;

    // ── Group 200 — Device Control ────────────────────────────────────────────
    constexpr uint16_t CMD_INIT_DEVICE        = 1;
    constexpr uint16_t RESP_INIT_DEVICE       = 2;
    constexpr uint16_t CMD_SET_MODE           = 3;
    constexpr uint16_t RESP_SET_MODE          = 4;
    constexpr uint16_t CMD_SHUTDOWN           = 5;
    constexpr uint16_t RESP_SHUTDOWN          = 6;
    constexpr uint16_t CMD_GET_STATUS         = 7;
    constexpr uint16_t RESP_STATUS            = 8;

    // ── Group 201 — RF Scan ───────────────────────────────────────────────────
    constexpr uint16_t CMD_START_SCAN         = 1;
    constexpr uint16_t RESP_SCAN_ACK          = 2;
    constexpr uint16_t CMD_STOP_SCAN          = 3;
    constexpr uint16_t RESP_STOP_ACK          = 4;
    constexpr uint16_t CMD_SET_SCAN_RANGE     = 5;
    constexpr uint16_t RESP_SET_SCAN_RANGE    = 6;

    // ── Group 202 — Signal Data ───────────────────────────────────────────────
    constexpr uint16_t CMD_REQUEST_DETECTIONS = 1;
    constexpr uint16_t RESP_DETECTIONS        = 2;
    constexpr uint16_t CMD_REQUEST_SPECTRUM   = 3;
    constexpr uint16_t RESP_SPECTRUM          = 4;

    // ── Group 203 — Diagnostics ───────────────────────────────────────────────
    constexpr uint16_t CMD_GET_HEALTH         = 1;
    constexpr uint16_t RESP_HEALTH            = 2;
    constexpr uint16_t CMD_RUN_SELF_TEST      = 3;
    constexpr uint16_t RESP_SELF_TEST         = 4;

    // ── RDFS operating modes (used in CMD_SET_MODE payload) ──────────────────
    constexpr uint8_t MODE_STANDBY            = 0;
    constexpr uint8_t MODE_SEARCH             = 1;
    constexpr uint8_t MODE_TRACK              = 2;
    constexpr uint8_t MODE_CALIBRATE          = 3;

    // ── Status codes ─────────────────────────────────────────────────────────
    constexpr uint16_t STATUS_OK              = 0;
    constexpr uint16_t STATUS_INVALID_PARAM   = 1;
    constexpr uint16_t STATUS_DEVICE_BUSY     = 2;
    constexpr uint16_t STATUS_HW_FAULT        = 3;
    constexpr uint16_t STATUS_NOT_READY       = 4;

} // namespace rdfs
